src/js/editable-element/controller.js
src/js/icons.js
src/js/module.js
src/js/themes.js

In our project, we use font-awesome instead of glyphicons. I added the ability to choose an icon set. More can be easily added

Add the ability to choose external icon sets. Support font awesome

---

src/js/editable-element/controller.js
src/js/editable-form/controller.js

added setTimeout() to call $hide on another stack

---

Gruntfile.js

Copy original and minified css to the `dist` folder.
https://github.com/vitalets/angular-xeditable/issues/294

Issue 294: Add minified versions of css

---

LICENSE
readme.md

Adding full MIT license

---

dist/js/xeditable.js

Fix radiolist issues when not using default angular symbol.

Fix radiolist

---

src/js/themes.js

Also updated paths in `Gruntfile.js` and `jsdoc.conf.json` to refer to correct node modules.
I only included newly built js files in `dist` folder and dropped other changes made by running `grunt build`.

Added semantic-ui theme (http://semantic-ui.com).

---

docs/demos/html5-inputs/controller.js
docs/demos/html5-inputs/desc.md
docs/demos/html5-inputs/test.js
docs/demos/html5-inputs/view.html
index.html
src/js/themes.js

#424  - Fix support for password fields

424 - Fix support for password fields

---

package.json

Hello. I improved package.json so not it will be easy to maintain npm package after we will have contributors rights to angular-xeditable npm package. I saw that you use lib folder for dependencies, so I added them as well in package.json. I used version as close as possible to used by you in lib folder. Do you thought about getting dependencies like bootstrap, moment, jquery using bower/npm? Cheers

Improved package.json

---

docs/demos/dev-select/view.html
docs/demos/uiselect/controller.js
docs/demos/uiselect/desc.md
docs/demos/uiselect/test.js
docs/demos/uiselect/view.html
docs/jade/overview.jade
docs/jade/scripts-dev.jade
docs/jade/scripts-prod.jade
docs/js/app.js
docs/js/structure.js
libs/ui-select/0.16.0/select.css
libs/ui-select/0.16.0/select.js
readme.md
src/js/directives/uiselect.js
test/e2e/dev-test.html
test/e2e/docs-test.html

Added support for ui-select.
This takes the changes in PR #300 and makes them work.
This fixes #211 and #436.

Added support for ui-select

---

docs/demos/bsdate/desc.md
docs/demos/dev-bsdate/controller.js
docs/demos/dev-bsdate/test.js
docs/demos/dev-bsdate/view.html
docs/demos/dev-select/controller.js
docs/demos/dev-select/test.js
docs/demos/dev-select/view.html
docs/demos/select-local/desc.md
src/js/directives/bsdate.js
src/js/directives/select.js

- Added on-change support for bsdate
- Added placeholder support for editable-select
- Added tests for new functionality
- This closes #461, #423, #223, #429

Added on-change support for bsdate and placeholder support for editable-select

---

docs/demos/html5-inputs/controller.js
docs/demos/html5-inputs/desc.md
docs/demos/html5-inputs/test.js
docs/demos/html5-inputs/view.html
src/js/directives/input.js
src/js/themes.js

- Added support for datetime-local input
- Updated ng-show to ng-if in template themes.  This reduced the watcher memory leak by 1.
- Fixes #266, #325

Added support for datetime-local input

---

src/js/directives/uiselect.js

updated directives/uiselect.js

added ability to add more then one editable-ui-select component on the same page.

---

docs/demos/dev-text/test.js
docs/demos/dev-text/view.html
docs/demos/text-customize/desc.md
docs/demos/text-customize/test.js
docs/demos/text-customize/view.html
src/js/directives/input.js
src/js/editable-element/controller.js

- Added ability to add classes to the containing form of the editable input.
- Manually remove the watcher for "has-error" to prevent a memory leak on it.
- Fixes #476

Added ability to add classes to the containing form of the editable input

---

docs/demos/dev-bsdate/controller.js
docs/demos/dev-bsdate/test.js
docs/demos/dev-bsdate/view.html
docs/demos/dev-uiselect/test.js
docs/demos/editable-popover/test.js
src/css/xeditable.css
src/js/editable-element/controller.js

- Vertical Scrollbar in Textarea in IE11 fix
- Fixed editable-popover tests
- Updated dev-bsdate tests
- Removed code that looped through watchers.  No longer needed due to #489
- Fixes #239, #498

Vertical Scrollbar in Textarea in IE11 fix

---

docs/demos/dev-bsdate/view.html
src/js/directives/checkbox.js
src/js/editable-element/controller.js

Wrap checkbox text in a span to allow for styling

---

docs/demos/dev-bsdate/test.js
docs/demos/dev-bsdate/view.html
src/js/directives/bsdate.js

Added support for e-style attribute for bsdate.
Fixes #503

Support styling of the bsdate textbox

---

docs/demos/dev-theme/controller.js
docs/demos/dev-theme/desc.md
docs/demos/dev-theme/test.js
docs/demos/dev-theme/view.html
docs/jade/themes.jade
docs/js/structure.js
src/js/editable-element/controller.js
src/js/editable-element/directive.js

Add editable-theme attribute to allow overriding of theme per control..
Fixes #382

Add editable-theme attribute to allow overriding of theme per control.

---

docs/css/docs.css
docs/demos/dev-text/test.js
docs/demos/dev-text/view.html
docs/demos/text-customize/desc.md
docs/demos/text-customize/view.html
docs/jade/themes.jade
src/css/xeditable.css
src/js/directives/input.js
src/js/editable-element/controller.js
src/js/icons.js
src/js/module.js
src/js/themes.js

- Add title to form buttons
- Add aria-label to form buttons
- Add configuration to display reset button
- Fix bstime css issue
- Add support for simple bootstrap input groups
- Closes #341

Added title and aria-label to form buttons

---

docs/demos/dev-uiselect/view.html
src/js/directives/uiselect.js

I have added two commits.
The first adds complexity to docs/demos/uiselect/view.html in order to recreate the issue described in #551 during automated testing.
The second addresses the issue described in #551.

Address #551 - editable-ui-select names must be unique across the application

---

docs/demos/dev-checklist/controller.js
docs/demos/dev-checklist/test.js
docs/demos/dev-checklist/view.html
docs/demos/dev-radiolist/controller.js
docs/demos/dev-radiolist/test.js
docs/demos/dev-radiolist/view.html
docs/jade/reference.jade
docs/jade/themes.jade
docs/js/structure.js
libs/checklist-model.js
src/js/directives/checklist.js
src/js/directives/input.js
src/js/directives/radiolist.js
src/js/module.js

- Use interpolate begin/end symbol in editableRange and editableRadioList
- Add ng-change support to radiolist
- Add ng-change support to checklist
- Added editableOptions to documentation
- Updated checklist-model.js to 0.10.0
- Closes #239

Use interpolate begin/end symbol in editableRange and editableRadioList

---

src/js/directives/ngtags.js
src/js/editable-element/controller.js

- Fix focus for radiolist/checklist/bsdate/tagsinput
- Updated ngTagsInput to have same changes made to uiSelect
- Closes #260

Fix focus for radiolist/checklist/bsdate/tagsinput

---

docs/css/docs.css
docs/demos/checklist/desc.md
docs/demos/dev-checklist/controller.js
docs/demos/dev-checklist/test.js
docs/demos/dev-checklist/view.html
docs/demos/editable-form/view.html
docs/demos/html5-inputs/view.html
docs/demos/onaftersave/view.html
docs/demos/onbeforesave/view.html
docs/demos/text-btn/view.html
docs/demos/text-customize/view.html
docs/demos/text-simple/view.html
docs/demos/textarea/view.html
docs/demos/typeahead/view.html
docs/demos/validate-local/view.html
docs/demos/validate-remote/view.html
src/js/directives/checklist.js

- Add support for checklist-comparator to editable-checklist
- Fix some layout issues of the demo site on phones
- Closes #558, #183

Add support for checklist-comparator to editable-checklist

---

docs/demos/dev-textarea/test.js
docs/demos/dev-textarea/view.html
docs/demos/textarea/desc.md
src/js/directives/textarea.js

Add option to submit editable textarea on enter
Closes #184

Add option to submit editable textarea on enter

---

docs/demos/dev-theme/test.js
docs/demos/dev-theme/view.html
docs/jade/scripts-dev.jade
docs/jade/themes.jade
src/js/editable-element/controller.js
test/e2e/dev-test.html

Also fixed icon_set value if theme is set via the attribute.
The theme_name detection could be made more pretty, but this should work...

Added possibility to set icon_set via attribute

---

docs/jade/overview.jade

- Updated dependency documentation
- Closes #524

Updated dependency documentation

---

docs/demos/html5-inputs/view.html
src/js/editable-element/controller.js
src/js/editable-form/controller.js
src/js/module.js

Correctly set caret position to end of input
Closes #584

Correctly set caret position to end of input

---

CONTRIBUTING.md
readme.md
src/js/directives/input.js

- Support tab for submit=blur
- Added contributing.md
- Closes #446

Support tab for submit=blur

---

CONTRIBUTING.md
bower.json
docs/demos/dev-textarea/test.js
docs/jade/scripts-dev.jade
docs/jade/scripts-prod.jade
docs/js/app.js
src/js/directives/combodate.js

Fixed $sce error in console when running dev tests.
Fixed errors when running tests in Safari.

Updated tests

---

docs/demos/dev-editable-row/controller.js
docs/demos/dev-editable-row/test.js
src/js/editable-element/controller.js
src/js/themes.js

-  Add support for HTML error messages
- Closes #160

Add support for HTML error messages

---

docs/demos/dev-text/view.html
src/js/directives/input.js
src/js/directives/textarea.js

- Add support for submit on tab for textarea
- Only submit on tab when blur = submit
- Closes #603, #604

Add support for submit on tab for textarea

---

docs/demos/dev-radiolist/test.js
docs/demos/dev-radiolist/view.html
docs/jade/overview.jade
src/js/directives/radiolist.js

- Added support for name on radiolist
- Closes #231

Added support for name on radiolist

---

docs/demos/dev-ngtags/test.js
docs/demos/ngtags/test.js
docs/demos/ngtags/view.html
src/js/directives/ngtags.js

- Fix cancel not cancelling for ngTagsInput
- Closes #617

Fix cancel not cancelling for ngTagsInput

---

docs/demos/combodate/test.js
src/js/directives/combodate.js

- Handle empty date values in combodate
- Fixes #636

Handle empty date values in combodate

---

docs/css/docs.css
docs/demos/combodate/test.js
docs/demos/dev-bsdate/test.js
docs/demos/dev-bsdate/view.html
docs/demos/html5-inputs/controller.js
docs/demos/html5-inputs/test.js
docs/demos/html5-inputs/view.html
docs/js/structure.js
src/js/directives/bsdate.js
src/js/editable-element/controller.js

- Update bsdate to work with no buttons and submit on blur
- Updated documentation to include support for input type=file
- Updated jsfiddle links to new working fiddles
- Updated determination of blur value
- Fixes #646, #645, #647, #285, #545

Update bsdate to work with no buttons and submit on blur

---

docs/css/docs.css
docs/demos/editable-popover/desc.md
docs/demos/uipopover/controller.js
docs/demos/uipopover/desc.md
docs/demos/uipopover/test.js
docs/demos/uipopover/view.html
docs/js/structure.js
src/css/xeditable.css
src/js/editable-element/controller.js
test/e2e/dev-test.html
test/e2e/docs-test.html

- Added support for ui-boostrap popover
- Fixes #621

Added support for ui-boostrap popover

---

docs/demos/dev-uiselect/test.js
docs/demos/dev-uiselect/view.html
docs/demos/uidate/test.js
docs/jade/scripts-prod.jade
docs/js/app.js
src/js/directives/uiselect.js
test/e2e/dev-test.html
test/e2e/docs-test.html

- Added no buttons support for ui-select
- Fixed documentation for ui-date
- Fixes #572

Added no buttons support for ui-select

---

docs/demos/dev-combodate/controller.js
docs/demos/dev-combodate/test.js
docs/demos/dev-combodate/view.html
src/js/directives/combodate.js

fix combodate not updating value if the combobox is not changed

---

docs/demos/e-single/controller.js
docs/demos/e-single/desc.md
docs/demos/e-single/test.js
docs/demos/e-single/view.html
docs/js/structure.js
test/e2e/dev-test.html
test/e2e/docs-test.html

Add e-single documentation

---

docs/demos/dev-text/test.js
docs/demos/dev-textarea/test.js
docs/demos/dev-textarea/view.html
src/js/directives/combodate.js
src/js/directives/input.js
src/js/directives/textarea.js

- Fix e-formclass for textarea
- Fixes #689

Fix e-formclass for textarea

---

CONTRIBUTING.md

•	Update live template links
•	Fixes #692

Update live template links

---

docs/jade/getstarted.jade
docs/jade/reference.jade
docs/jade/themes.jade
docs/js/app.js

- Update examples to use string Angular dependency injection
- Fixes #695

Update examples to use string Angular dependency injection

---

docs/js/app.js
src/js/editable-element/directive.js

- Fix Node/Phantomjs/Karma syntax error
- Fixes #700

Fix Node/Phantomjs/Karma syntax error

---

docs/demos/dev-combodate/controller.js
docs/demos/dev-combodate/test.js
docs/demos/dev-combodate/view.html
src/js/directives/combodate.js

- Fix editable-combodate for single date fields
- Fixes #705, #706

Fix editable-combodate for single date fields

---

docs/demos/dev-combodate/test.js
docs/demos/dev-text/controller.js
docs/demos/dev-text/test.js
docs/demos/dev-text/view.html
src/js/directives/input.js

- Add ng-bind for input group
- Fixes #713

Add ng-bind for input group

---

src/js/directives/bsdate.js

- Add datepicker-template-url support for editableBsDate
- Fixes #728

Add datepicker-template-url support for editableBsDate

---

starter/index.html

- Update angular version in starter template
- Fixes #731

Fix starter template

---

docs/demos/checklist/controller.js
docs/demos/checklist/desc.md
docs/demos/checklist/view.html
src/js/directives/checklist.js

* allow users to disable checkboxes based on a condition.
* Update the docs
fixes #744

allow users to disable checkboxes based on a condition

---

docs/demos/bsdate/desc.md
docs/demos/bstime/desc.md
docs/demos/checklist/controller.js
docs/demos/checklist/test.js
docs/demos/dev-theme/test.js
docs/demos/dev-theme/view.html
docs/demos/typeahead/desc.md
docs/demos/uidate/test.js
docs/jade/getstarted.jade
docs/jade/overview.jade
docs/jade/scripts-dev.jade
docs/jade/scripts-prod.jade
docs/jade/themes.jade
docs/js/app.js
readme.md
src/js/directives/bsdate.js
src/js/icons.js
src/js/module.js
src/js/themes.js
starter/app.js

Added Bootstrap 4 theme.
Closes #746

Add Bootstrap 4 template

---

docs/css/docs.css
docs/demos/uipopover/desc.md
docs/demos/uipopover/test.js
docs/demos/uipopover/view.html
src/js/editable-element/controller.js

Fix rendering of editable ui-bootstrap popover

---

docs/demos/dev-radiolist/controller.js
docs/demos/dev-radiolist/test.js
docs/demos/dev-radiolist/view.html
src/js/directives/radiolist.js

Fix radiolist issue with string values
Fixes #694, #752

Fix radiolist issue with string values

---

src/js/editable-form/controller.js

Fix activationEvent of focus doesn't allow editing.
Fixes #465

Fix activationEvent of focus doesn't allow editing.

---

src/js/editable-element/controller.js
src/js/editable-form/controller.js

issue - #757
**problem**: when you are doing mouse up outside on input box, submit is triggering.
**reason**: because we are listening on click event - line: 1485 - $document.bind('click', function (e) { ....
**solution**: listen to mousedown like - $document.bind('mousedown', function (e) {

Control deselects when navigating outside the area - mouseup on outside #757

---

docs/demos/dev-checklist/view.html
src/js/directives/checklist.js

Allow name attribute on checklist
Fixes #769

Allow name attribute on checklist
