vitalets/angular-xeditable

src/js/themes.js
Added cases for editableBsdate and editableBstime in the directive-name switch statement in the BS3 theme to add the 'form-control' class to the input element generated.
[before](http://i.imgur.com/agFFScG.png)
(font looks odd because it's in an h3)
[after](http://i.imgur.com/EUHFzqL)
=> Applying 'form-control to bsdate in bs3

src/js/editable-element/controller.js
`angular.copy` must not be used (as you also wrote) when dealing with (heavy) objects. there is another place where using `angular.copy`, but validation is performed there.
=> Fixed angular.copy issue

src/js/editable-element/controller.js, src/js/editable-form/controller.js, src/js/editable-form/directive.js
Issue on IE8 (maybe IE10 emulation only): click inside editable text
input triggers onblur (field is, consequently, no more editable).
=> Fix IE8 accidental onblur.

src/js/editable-element/directive.js
This little changes allow to bind form controller not only to $parent scope.
For example this will work as expected, and ng-if created scope not absorb "item.amountField" as its own property.
```html
<a editable-number="item.amount" 
e-required 
e-min="0"
e-form="item.amountField"
ng-if="item.isEnabled">
{{ (item.amount }}
</a>
<button class="btn btn-default" ng-click="item.amountField.$show()" ng-if="item.isEnabled"> 
Activate
</button>
```
=> Make e-form more flexible, when there isn't parent form element

src/js/editable-element/controller.js
Currently if the main model is updated the forms view value doesn't get updated with the new value, the inputs scope and $data reflect the update but not the view as shown in this [issue](https://github.com/vitalets/angular-xeditable/issues/130)
=> Fix for issue #130 - Updating form view value.

docs/jade/reference.jade
The syntax in the examples of Properties and Methods is invalid, the dot is unnecessary.
"myform.[property]" should be "myform[property]"
"myform.[method]" should be "myform[method]"
=> docs(reference): fix properties and methods examples

src/js/directives/checkbox.js, src/js/themes.js
This is a PR for issue https://github.com/vitalets/angular-xeditable/issues/213
I would have removed the span in the bs3 specific theme but since the directive elements are created after the ```postrender``` is called... I can't :-(
=> Fix checkbox form alignment

src/js/directives/radiolist.js
Users can use e-ng-disabled with angular expressions to disable radio-button elements.
=> Added support for ng-disabled to radiolist

index.html, src/js/editable-element/directive.js, src/js/module.js
activation event can now be choosen via <code>editableOptions.activationEvent = '...'</code> and defaults to <code>'click'</code>!
documentation included.
=> fix #225 'Feature: choose event to activate edit mode'

src/js/editable-element/directive.js
Reverts vitalets/angular-xeditable#212
This is a breaking change that creates the issue described in #263
=> Revert "Make e-form more flexible, when there isn't parent form element"

index.html, src/js/editable-element/directive.js
This fix addresses http://github.com/vitalets/angular-xeditable/issues/6)
To use, simply include e-single on any element you wish to 'ignore' the hasForm variable.
Example:
`<a href="#" editable-text="person.FirstName" e-required e-placeholder="First Name" e-single>{{ person.FirstName || \'First Name\' }}</a>`
Passes JShint, also i wanted to create a branch on my fork for this fix, so that explains 2 pull requests, one closed.
=> Fix for #6 unable to use single xeditable form elements (without whole form editing) + use angular's form validation #314

src/js/editable-form/controller.js
When adding a new item to an editable form, the waiting state of the new item needs to match the waiting state of the rest of the form.
=> Make new editables added to a form match the waiting state of the form

docs/demos/combodate/desc.md, src/js/directives/combodate.js
Currently maxYear is hardcoded to 2015, making the control unusable for us. Not sure what the best option is. This pull request adds pass through of `e-min/max-year` attributes to combodate control.
=> Allow passing min/maxYear to combodate

src/js/editable-form/controller.js
Checking for isDefaultPrevented() causes the check for form blur to be avoided in many cases where the form actually is blurred and the form should be canceled if the user has set `blur="cancel"` on the editable form.
This is the only place in the code that checks isDefaultPrevented(), and it is not required to prevent blur on a right click.
=> Remove `isDefaultPrevented()` check

src/js/editable-element/directive.js
I bumped into a problem with xeditable today when using it for editing columns in a row as explained here https://vitalets.github.io/angular-xeditable/#editable-row. 
The use case is when the editable element is outside of the form, i.e. something like this
```
<td>
<span editable-text="user.name" e-name="name" e-form="rowform">
{{ user.name || 'empty' }}
</span>
</td>
<td style="white-space: nowrap">
<form editable-form name="rowform" ng-show="rowform.$visible" class="form-buttons form-inline">
</form>
<div class="buttons" ng-show="!rowform.$visible">
<button class="btn btn-primary" ng-click="rowform.$show()">edit</button>
</div>
</td>
```
Now this works fine when all of the HTML is in DOM when the directives compile and link, but in my case I'm using these directives in a piece of …
=> Fix finding form controller when elements not yet in DOM

src/js/editable-element/directive.js
Now it checks the variable at the moment of opening the input (clicking on the editable text) instead of checking the variable when the directive instance is created.
=> Fixed text-disable so it "Watches" the actual value of the edit-disabled attribute instead of the initial value

src/js/editable-element/directive.js
Publishing local `$form` to some variable is everything ok, but doing to some object property does no work
```js
<span editable-text="user.name" e-form="form"> 
<span editable-text="user.name" e-form="ctrl.form"> 
```
plunker: http://plnkr.co/edit/jMTP57413JZPFmsVJlZu?p=preview
=> Make 'e-form' publish local $form even if specify object property

docs/demos/combodate/desc.md, docs/demos/dev-text/test.js, docs/demos/dev-text/view.html, docs/demos/edit-disabled/controller.js, docs/demos/edit-disabled/desc.md, docs/demos/edit-disabled/test.js, docs/demos/edit-disabled/view.html, docs/demos/text-simple/view.html, docs/js/structure.js, src/js/directives/input.js, src/js/editable-element/controller.js
- Added documentation for edit-disabled
- Updated combodate documentation
- Reduced $error watcher leak by 1 by removing the controlsEl element before removing the editorEl element
- Fixes #471
=> Added ability to add a label to an input

docs/demos/checkbox/test.js, docs/demos/dev-form/test.js, docs/demos/dev-select/test.js, docs/demos/dev-text/test.js, docs/demos/editable-column/test.js, docs/demos/editable-form/test.js, docs/demos/editable-row/test.js, docs/demos/editable-table/test.js, docs/demos/onaftersave/test.js, docs/demos/onbeforesave/test.js, docs/demos/radiolist/test.js, docs/demos/select-local/test.js, docs/demos/select-multiple/test.js, docs/demos/select-nobuttons/test.js, docs/demos/select-remote/test.js, docs/demos/text-btn/test.js, docs/demos/text-simple/test.js, docs/demos/textarea/test.js, docs/demos/typeahead/test.js, docs/demos/validate-local/test.js, docs/demos/validate-remote/test.js, src/js/directives/bsdate.js, src/js/directives/checklist.js, src/js/directives/radiolist.js, src/js/directives/uiselect.js, src/js/editable-element/controller.js
This merge request probably solves Issue #364 . Currently when entering the `editable` mode, the `element` is `$compile`d with the same `$scope` as before and is not being destroyed properly when exiting `editable` mode.  This fix is the same fix made in issue #158 but the merge request hasn't been accepted due to other problems ( i'm not sure why ).
I think this memory leak is fatal for pages which use many inputs on the same page (it'll create lots of `$$watchers` every time entering `editable` mode).  I'm not quite sure about the side effects so it would be very helpful if somebody could point any problems about this change.
Thanks in advance.
**Edited**
It seems this same fix has been removed due to the fix of issue #265 .  I'll have to take a look at the issue a little more.
=> Fix - Memory leak when ending editing by destroying the scope.

src/css/xeditable.css
- Fix editable-popoup css to work better on phone
- Fix link css to only apply to links directly contained by the popover-wrapper
- Closes #519 and #522
=> Updated css for editable-popup to work better on phones

docs/demos/bsdate/view.html, docs/demos/dev-bsdate/view.html, src/js/directives/bsdate.js
The datepicker and the popup have default settings in their constants uibDatepickerConfig and uibDatepickerPopupConfig. They can be set for all datepickers in the whole angular app.
Using uibDatepickerConfig and uibDatepickerPopupConfig makes the datepicker generated by xeditable consistent with the standard datepickers in an app without doing anything - no need to set every single setting for the xeditable datepicker.
Also the generated attributes, that don't have value different from the default, don't need to be set so they won't.
=> Use datepicker's default settings

bower.json, docs/demos/uidate/controller.js, docs/demos/uidate/desc.md, docs/demos/uidate/test.js, docs/demos/uidate/view.html, docs/jade/scripts-dev.jade, docs/js/structure.js, readme.md, src/js/directives/uidate.js
Implementation of editableUiDate directive to be able to use [jQuery UI datepicker for AngularJS](https://github.com/angular-ui/ui-date) 
To use the new directive you simple do this:
`<span editable-uidate="yourModel" e-ui-date="datePickerConfig">{{ yourModel }}</span> `
And use it as you normally will use the jQuery UI datepicker.
=> Added support to jQuery UI Datepicker for AngularJS

docs/demos/dev-bsdate/controller.js, docs/demos/dev-bsdate/test.js, docs/demos/dev-bsdate/view.html, src/js/directives/bsdate.js
Add support for the angular datepicker-popup component's `alt-input-formats` attribute that was not previously supported by angular-xeditable's bsdate component.
=> Add support for alt-input-formats to bsdate.

src/js/directives/bsdate.js
Hi, here is a pull request that corrects the reading of the datepicker-append-to-body attribute. Without this using e-datepicker-append-to-body is not recognized. There was a previous similar pull request in Nov 2016 but it hasn't been integrated because of conflicts. Hopefully this one works.
Thank you.
=> Correction of the reading of the datepicker-append-to-body attribute.

index.js, package.json, readme.md
With this PR it is possible to to do:
```JS
import angularXeditable from 'angular-xeditable';
angular.module('app', [angularXeditable]);
```
and have on less verbose string to worry about in Angular 1 ;)
=> Change main entry to index.js and export module name
